
CREATE TABLE CLIENTE (
    ID_CLI NUMBER GENERATED ALWAYS AS IDENTITY,
    DPI_CLI VARCHAR2(20) UNIQUE,
    NOMBRE_CLI VARCHAR2(100),
    TELEFONO_CLI VARCHAR2(15),
    CORREO_CLI VARCHAR2(100),
    DIRECCION_CLI VARCHAR2(200),
    SALDO_PUNTO_CLI NUMBER(5) DEFAULT 0,
    ESTADO_CLI VARCHAR2(1)
);
